In [7]:
import numpy as np 
a =np.array([1,2,3])
a 
#question1

array([1, 2, 3])

In [9]:
import numpy as np 
a= np.array ([[0, 10, 20], [ 30, 40, 50]])
print ( "Original array : ")
print (a)
y=10
print (" values bigger than 10 =", a [a>y])
#question2

Original array : 
[[ 0 10 20]
 [30 40 50]]
 values bigger than 10 = [20 30 40 50]


In [11]:
import numpy as np
a= np.array ([[3.7], [7.9]], dtype = np.float64)
b= np.array ([[3.7], [7.9]], dtype = np.float64)
z= a+b 
print (z)
#question4

[[ 7.4]
 [15.8]]


In [12]:
import numpy as np
x = np.random.rand (5,10)
y = x-x.mean (axis=1, keepdims= True )
print (y)
#question5

[[ 0.37284688  0.32280765 -0.37148023 -0.13280611  0.13269218 -0.37738704
  -0.18642388  0.48626215  0.07369565 -0.32020724]
 [-0.37639916  0.08636564 -0.5410828   0.27168662  0.08849913  0.28099531
   0.21855861  0.00313566 -0.28203933  0.25028031]
 [ 0.43582523  0.27787801  0.1808463  -0.22998211 -0.30784966 -0.20227553
   0.12627292 -0.10430157  0.16287926 -0.33929284]
 [-0.09859989 -0.0671167   0.4690552   0.30574109 -0.33885784  0.17599817
   0.00272745 -0.29536055 -0.41399803  0.26041111]
 [-0.11510616  0.02411291  0.19069741  0.44003269  0.31593723 -0.40605775
  -0.03564589  0.2347995  -0.26207283 -0.38669711]]


In [28]:
#question3 
array1 = np.array ([[ 9, 8, 2], [4, 6, 3 ]])
print (type(array1))
print ( array1 )
x1 = int (input ())
for x in array1 : 
    for y in x : 
          if x1<y :
                print (y,end= "\n")
            

<class 'numpy.ndarray'>
[[9 8 2]
 [4 6 3]]
3
[9 8 2]
9
8
[4 6 3]
4
6


In [13]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a[0,2])

2


In [21]:
n = [1, 3, 9 ]
for i in n: 
    print (i)

1
3
9
